#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -ue
set -o pipefail
echo "Begin: install and configure SSH"

augtool <<EOF
set /files/etc/ssh/sshd_config/UsePAM yes

set /files/etc/ssh/sshd_config/ChallengeResponseAuthentication no
set /files/etc/ssh/sshd_config/AllowAgentForwarding no
set /files/etc/ssh/sshd_config/X11Forwarding no
set /files/etc/ssh/sshd_config/PermitRootLogin no
set /files/etc/ssh/sshd_config/PubkeyAuthentication no
set /files/etc/ssh/sshd_config/RhostsRSAAuthentication no
set /files/etc/ssh/sshd_config/HostbasedAuthentication no
set /files/etc/ssh/sshd_config/PermitEmptyPasswords no
set /files/etc/ssh/sshd_config/PasswordAuthentication no
set /files/etc/ssh/sshd_config/X11Forwarding no
set /files/etc/ssh/sshd_config/PrintMotd no
set /files/etc/ssh/sshd_config/PrintLastLog no
set /files/etc/ssh/sshd_config/UseDNS no

set /files/etc/ssh/sshd_config/GSSAPIAuthentication yes
set /files/etc/ssh/sshd_config/GSSAPICleanupCredentials yes
set /files/etc/ssh/sshd_config/UsePrivilegeSeparation yes
set /files/etc/ssh/sshd_config/AuthorizedKeysFile %h/.ssh/authorized_keys

set /files/etc/ssh/sshd_config/KexAlgorithms/1 curve25519-sha256@libssh.org
set /files/etc/ssh/sshd_config/KexAlgorithms/2 diffie-hellman-group-exchange-sha256

set /files/etc/ssh/sshd_config/Ciphers/1 chacha20-poly1305@openssh.com
set /files/etc/ssh/sshd_config/Ciphers/2 aes256-gcm@openssh.com
set /files/etc/ssh/sshd_config/Ciphers/3 aes256-ctr
set /files/etc/ssh/sshd_config/Ciphers/4 aes192-ctr

set /files/etc/ssh/sshd_config/MACs/1 hmac-sha2-512-etm@openssh.com
set /files/etc/ssh/sshd_config/MACs/2 hmac-sha2-256-etm@openssh.com
set /files/etc/ssh/sshd_config/MACs/3 hmac-ripemd160-etm@openssh.com
set /files/etc/ssh/sshd_config/MACs/4 umac-128-etm@openssh.com
set /files/etc/ssh/sshd_config/MACs/5 hmac-sha2-512
set /files/etc/ssh/sshd_config/MACs/6 hmac-sha2-256
set /files/etc/ssh/sshd_config/MACs/7 hmac-ripemd160
set /files/etc/ssh/sshd_config/MACs/8 umac-128@openssh.com

set /files/etc/ssh/sshd_config/Port 22
set /files/etc/ssh/sshd_config/Protocol 2
set /files/etc/ssh/sshd_config/HostKey /etc/ssh/ssh_host_ed25519_key
set /files/etc/ssh/sshd_config/HostKey /etc/ssh/ssh_host_rsa_key

set /files/etc/ssh/sshd_config/KeyRegenerationInterval 3600
set /files/etc/ssh/sshd_config/ServerKeyBits 1024

set /files/etc/ssh/sshd_config/SyslogFacility AUTH
set /files/etc/ssh/sshd_config/LogLevel INFO

set /files/etc/ssh/sshd_config/LoginGraceTime 120
set /files/etc/ssh/sshd_config/StrictModes yes

set /files/etc/ssh/sshd_config/IgnoreRhosts yes

set /files/etc/ssh/sshd_config/X11DisplayOffset 10
set /files/etc/ssh/sshd_config/TCPKeepAlive yes

save
EOF

echo "End: install and configure SSH"

:
